server {
    listen 50080 ssl;
    listen [::]:50080 ssl;
    server_name 47.111.139.230;

    ssl_certificate /etc/data-for-didi-mobile-tls/certs/server-fullchain.pem;
    ssl_certificate_key /etc/data-for-didi-mobile-tls/private/server.key;
    ssl_trusted_certificate /etc/data-for-didi-mobile-tls/certs/ca.crt;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:MOBILE_SOURCE_TLS:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;

    client_max_body_size 2m;
    access_log /xp/server/nginx/logs/data-for-didi-mobile-source.access.log;
    error_log /xp/server/nginx/logs/data-for-didi-mobile-source.error.log warn;

    location / {
        proxy_pass http://127.0.0.1:50081;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Connection "";
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
        proxy_send_timeout 30s;
    }
}
